"""cadre/verify_palette.py — verify AIAgent provider/model resolution against
this host, then write the confirmed pairs to ~/.cadre/palette.yaml.

Caller-layer module (KTD4). Moved unchanged from the retired host-verify
spike during the U5 packaging pass
(docs/plans/2026-07-04-003-feat-package-as-cadre-plan.md): an installed-package
module imports ``cadre.config`` natively, so the spike's repo-relative
``sys.path`` bootstrap is gone, and ``SAFE_TOOLSETS`` is now a top-level import
instead of a lazy one (only ``_agent``'s ``run_agent`` import stays lazy — that
dependency is host-only). Invoked via the installed console command:

    cadre verify-palette

RUNS ON THE HERMES HOST with the Hermes venv Python (the interpreter cadre was
pip-installed into — the load-bearing KTD2 install target):

    ~/.hermes/hermes-agent/venv/bin/python -m cadre.cli verify-palette

---

## Two cleanly separated pieces

**(1) Live verification** — not testable on the dev machine (no hermes-agent).
    `verify_candidates(candidates)` calls AIAgent on the Hermes host and returns
    a list of VerifyRecord. Never call this here; the test suite patches `_agent`.

**(2) Pure writer** — fully testable here with fake records.
    `write_palette(records, toolsets, path)` takes a record list + declared toolsets,
    filters to ok pairs + safe toolsets, and writes owner-only 0o600 YAML.

---

## One-time host workflow

1. `cadre setup` seeds ~/.cadre/palette-candidates.yaml from the installed
   package (or edit PROVIDERS in this file) with your real strings.
2. Run `cadre verify-palette` via the Hermes venv — verifies + writes
   ~/.cadre/palette.yaml. By default this verifies a capped subset (2 per
   provider, file order) rather than every discovered candidate; pass
   `--all` to verify everything. Previously-verified pairs still in the
   candidates file are always re-verified (cap-exempt) — a re-verify never
   silently shrinks an existing palette. On success (2+ providers verified), it also
   (re)generates ~/.cadre/fleets/palette-fleet.yaml — a tool-less smoke-test
   fleet with one lane per verified provider, ready to `cadre run` with zero
   editing (see cadre/palette_fleet.py).
3. The cadre-fleet skill reads palette.yaml; compose only from its contents.

---

## Format notes

* OAuth providers (xai, openai-codex, nous): provider + bare model id.
* OpenRouter: provider="openrouter" + full "vendor/model" slug.
* NEVER put API keys here — credentials live in Hermes auth/env.
"""

from __future__ import annotations

import contextlib
import io
import logging
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

import yaml

from cadre.approval import _parent_is_safe, _write_owner_only
from cadre.config import SAFE_TOOLSETS
from cadre.discover import _DEFAULT_CANDIDATES_PATH
from cadre.palette_fleet import write_palette_fleet
from cadre.policy import Policy, PolicyError, filter_pairs, load_policy, resolve_policy_path
from cadre.text_safety import sanitize as _sanitize

# Default palette output path.
_DEFAULT_PALETTE_PATH = Path("~/.cadre/palette.yaml")

# Default per-provider verify cap (R5): zero-touch discovery (#61) can surface
# ~70 candidates across a handful of providers; verifying every one before the
# palette is even usable is 70 paid calls. A named constant (not a bare literal
# in the function default) so the cap size can't drift out of sync between the
# actual cap and the banner message that reports it.
_DEFAULT_PER_PROVIDER_CAP = 2

# Honesty header for the written palette (KTD4): models are live-verified, but
# toolsets are only DECLARED + safe-filtered, never tool-probed (verify_candidates
# runs a no-tool chat). A model can resolve while its search tool is unprovisioned,
# so a lane reading that toolset can run silently ungrounded. The full fix is
# host-side per-toolset probing (see RUNBOOK); until then this warns the reader.
# Shared by write_palette (the verify path) and _prune_banned_from_palette (the
# all-banned prune path), so both write byte-identical headers.
_PALETTE_HEADER = (
    "# Cadre verified palette — generated by the verify step; do not hand-edit.\n"
    "# models:   provider/model pairs confirmed by a live chat call.\n"
    "# toolsets: DECLARED safe toolsets, NOT tool-probed — provision each in the\n"
    "#           Hermes profile (see RUNBOOK) or a lane using it runs silently\n"
    "#           ungrounded (answers from training knowledge, with no error).\n"
)

# ---------------------------------------------------------------------------
# Candidate pairs to verify on the host.
# Edit these (or use ~/.cadre/palette-candidates.yaml) before running.
# ---------------------------------------------------------------------------

PROVIDERS: list[tuple[str, str]] = [
    # ("xai", "grok-4.3"),
    # ("openrouter", "google/gemini-3-flash"),
]



# ---------------------------------------------------------------------------
# Record type
# ---------------------------------------------------------------------------


@dataclass
class VerifyRecord:
    """One verification outcome for a (provider, model) pair."""

    provider: str
    model: str
    ok: bool
    detail: str = field(default="")


# ---------------------------------------------------------------------------
# Live verification (NOT testable on dev; runs on Hermes host)
# ---------------------------------------------------------------------------


def _agent(provider: str, model: str, toolset: list[str] | None = None):
    """Build an AIAgent for verification. Import is lazy — never at module level.

    [] not None: in Hermes, enabled_toolsets=None enables EVERY toolset.
    An empty list (fail-closed zero tools) is the safe default for verification.
    """
    from run_agent import AIAgent  # noqa: PLC0415 — intentionally lazy

    return AIAgent(
        provider=provider,
        model=model,
        # [] not None: in Hermes, enabled_toolsets=None enables EVERY toolset.
        enabled_toolsets=list(toolset) if toolset else [],
        skip_memory=True,
        skip_context_files=True,
        quiet_mode=True,
    )


def verify_candidates(candidates: list[tuple[str, str]]) -> list[VerifyRecord]:
    """Verify each (provider, model) pair via AIAgent and return structured records.

    Each pair gets a VerifyRecord(ok=True/False, detail=...). Empty response
    (None or blank) is treated as ok=False. Exceptions are caught and recorded.

    Args:
        candidates: List of (provider, model) pairs to verify.

    Returns:
        List of VerifyRecord, one per candidate, in input order.
    """
    records: list[VerifyRecord] = []
    for provider, model in candidates:
        ok, detail = _verify_one(provider, model)
        # Candidate strings are discovery-sourced (#61) and detail derives from
        # provider output — both untrusted display input (KTD9): sanitize each
        # field, never the assembled line.
        if ok:
            print(f"  ✓ {_sanitize(provider)} / {_sanitize(model)}")
        else:
            print(
                f"  ✗ {_sanitize(provider)} / {_sanitize(model)}  "
                f"— skipped ({_sanitize(_short_reason(detail))})"
            )
        records.append(VerifyRecord(provider=provider, model=model, ok=ok, detail=detail))
    return records


def _verify_one(provider: str, model: str) -> tuple[bool, str]:
    """Run one verification chat call, SILENCING the provider's own output.

    A candidate the host doesn't support (e.g. a model your provider doesn't
    offer) makes AIAgent dump a multi-line error to stdout/stderr — which reads
    like a crash even though a skipped candidate is a normal outcome. Capture
    that output (and mute logging) so verify_candidates can print one calm line
    instead. Set ``CADRE_VERIFY_VERBOSE=1`` to see the provider output
    (sanitized — see below).

    Returns ``(ok, detail)``; never raises.
    """
    def _call() -> object:
        return _agent(provider, model).chat("Reply with the single word: ok")

    # Verbose: show the provider's own output (for debugging an unexpected
    # result) — SANITIZED, not raw (CodeRabbit #74): provider output is model
    # output, and every model-output terminal surface goes through the
    # text_safety chokepoint. sanitize() only strips escape/control bytes,
    # so the diagnostic value survives.
    if os.getenv("CADRE_VERIFY_VERBOSE"):
        sink = io.StringIO()
        try:
            with contextlib.redirect_stdout(sink), contextlib.redirect_stderr(sink):
                text = _call()
        except Exception as exc:  # noqa: BLE001
            if sink.getvalue():
                print(_sanitize(sink.getvalue()), end="")
            return False, f"{type(exc).__name__}: {exc}"
        if sink.getvalue():
            print(_sanitize(sink.getvalue()), end="")
        ok = bool(text and str(text).strip())
        return ok, (str(text)[:60] if ok else "empty response")

    # Default: capture the provider's output + mute logging so a skip is one calm
    # line — then mine the capture for the real reason (AIAgent usually logs the
    # error and returns None rather than raising, so the bare result is just None).
    sink = io.StringIO()
    logging.disable(logging.CRITICAL)
    try:
        with contextlib.redirect_stdout(sink), contextlib.redirect_stderr(sink):
            text = _call()
        ok = bool(text and str(text).strip())
        if ok:
            return True, str(text)[:60]
        return False, _reason_from_capture(sink.getvalue()) or "empty response"
    except Exception as exc:  # noqa: BLE001
        return False, f"{type(exc).__name__}: {exc}"
    finally:
        logging.disable(logging.NOTSET)


def _short_reason(detail: str) -> str:
    """A terse, one-line skip reason for DISPLAY — the last ': '-delimited segment
    (strips noise like an emoji/'Error'/'HTTP 4xx' prefix). The full detail is
    kept in the record."""
    msg = detail.rsplit(": ", 1)[-1].strip()
    return (msg[:70] + "…") if len(msg) > 71 else msg


def _reason_from_capture(captured: str) -> str:
    """Mine a calm one-line reason from suppressed provider output (or '')."""
    lines = [ln.strip() for ln in captured.splitlines() if ln.strip()]
    # Prefer the most specific phrasing, then a generic error/status line.
    for needle in ("not supported", "unauthor", "forbidden", "denied",
                   "invalid", "quota", "rate limit"):
        for ln in lines:
            if needle in ln.lower():
                return ln
    for ln in lines:
        low = ln.lower()
        if "error:" in low or "http 4" in low or "http 5" in low:
            return _short_reason(ln)
    return ""


# ---------------------------------------------------------------------------
# Pure writer (fully testable with fake records)
# ---------------------------------------------------------------------------


def write_palette(
    records: list[VerifyRecord],
    toolsets: list[str],
    path: Path | str,
) -> None:
    """Write the verified palette to ``path`` as owner-only YAML (0o600).

    Filters ``records`` to only ``ok=True`` pairs. Intersects ``toolsets`` with
    ``cadre.config.SAFE_TOOLSETS``, preserving input order (list
    comprehension, not set intersection — order is locked by the downstream
    schema). Raises ValueError (before any filesystem side-effects) if there are
    zero ok records.

    The written YAML has the locked schema::

        generated_at: "2026-06-18T14:30:00.123456"
        models:
          - provider: xai
            model: grok-4.3
          - provider: openrouter
            model: google/gemini-3-flash
        toolsets: [web, search, x_search, vision]

    Args:
        records: Verification records from ``verify_candidates`` (or test fakes).
        toolsets: Declared toolsets for this profile; non-safe names are dropped.
        path: Destination path for the palette YAML (parent is created if missing).

    Raises:
        ValueError: If there are no ``ok=True`` records (nothing to write).
        OSError: If ``path``'s parent directory is a symlink, is not owned by
            the current user, or is group/other-writable (``_parent_is_safe``);
            or if ``path`` itself is a symlink (``O_NOFOLLOW``).
    """
    # Validate BEFORE any side effects — zero ok records → don't write anything.
    ok_records = [r for r in records if r.ok]
    if not ok_records:
        raise ValueError(
            "no verified providers — palette not written; "
            "check candidates and host auth"
        )

    # Order-preserving safe-toolset filter (NOT set intersection).
    safe_toolsets = [t for t in toolsets if t in SAFE_TOOLSETS]

    # Build the palette dict in the locked field order.
    palette = {
        "generated_at": datetime.now().isoformat(),
        "models": [{"provider": r.provider, "model": r.model} for r in ok_records],
        "toolsets": safe_toolsets,
    }

    # Honesty header at the point of use (see _PALETTE_HEADER): toolsets are
    # declared + safe-filtered, never tool-probed.
    content = _PALETTE_HEADER + yaml.safe_dump(palette, sort_keys=False, allow_unicode=True)

    path = Path(path)

    # Create parent dir owner-only (mirror capture.py's prepare_run_dir umask discipline).
    old_umask = os.umask(0o077)
    try:
        path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)

        # Refuse to write into a group/other-writable (or foreign-owned) parent
        # (CodeRabbit, Major/Security) — mirrors approval.write_approval /
        # install_skill.install_skill's same guard. mkdir(exist_ok=True) tightens a
        # freshly-created dir to 0o700 but will NOT downgrade a pre-existing loose
        # one, and O_NOFOLLOW below only stops a symlink AT palette.yaml — it does
        # not protect against a loose parent a co-resident user could replant
        # through. Check AFTER mkdir so a just-created dir passes by construction
        # and only a pre-existing loose dir is refused.
        if not _parent_is_safe(str(path.parent)):
            raise OSError(
                f"{path.parent} is unsafe — it must be owned by you and not "
                "group/other-writable. Fix it, then re-run."
            )

        # Write owner-only at creation — never the momentary 0o644 a write-then-chmod
        # leaves under a default umask (mirrors capture._write exactly). O_NOFOLLOW
        # (not part of capture._write's base idiom) refuses to follow a symlink
        # planted at path — matching provision.write_config / _seed_files / the
        # approval-token writer's same guard.
        flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
        fd = os.open(path, flags, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        path.chmod(0o600)
    finally:
        os.umask(old_umask)


# ---------------------------------------------------------------------------
# Main — glues verify → write on the Hermes host
# ---------------------------------------------------------------------------


def _load_candidates(candidates_path: Path) -> tuple[list[tuple[str, str]], list[str]]:
    """Read candidate pairs and declared toolsets from the seed YAML.

    Returns (candidates, toolsets). Falls back to the module-level PROVIDERS
    if the seed file doesn't exist or has no candidates block.
    """
    if candidates_path.exists():
        data = yaml.safe_load(candidates_path.read_text(encoding="utf-8")) or {}
        if not isinstance(data, dict):
            # A non-mapping root (top-level list/scalar) has no candidates block;
            # `or {}` only catches None, so guard the type before calling .get().
            return PROVIDERS, []
        raw_candidates = data.get("candidates") or []
        candidates = [
            (c["provider"], c["model"])
            for c in raw_candidates
            if isinstance(c, dict) and c.get("provider") and c.get("model")
        ]
        raw_toolsets = data.get("toolsets") or []
        # Guard scalar toolsets: a bare string (e.g. `toolsets: web`) must NOT be
        # iterated char-by-char. Only accept a list; a scalar string is treated as
        # invalid and discarded.
        toolsets = [t for t in raw_toolsets if isinstance(t, str)] if isinstance(raw_toolsets, list) else []
        return candidates, toolsets
    # Fallback: module-level PROVIDERS (edit before running).
    return PROVIDERS, []


def _cap_candidates(
    candidates: list[tuple[str, str]],
    per_provider: int = _DEFAULT_PER_PROVIDER_CAP,
    always_keep: frozenset[tuple[str, str]] = frozenset(),
) -> list[tuple[str, str]]:
    """Order-preserving cap: keep the first ``per_provider`` candidates for each
    provider, in file order. Pure — no I/O, no printing, no live calls; sits
    between ``_load_candidates`` and ``verify_candidates`` (R5, KTD4). A
    provider with fewer than ``per_provider`` candidates is unaffected.

    ``always_keep`` pairs are kept regardless of the cap (they do not count
    toward it): the caller passes the EXISTING palette's pairs so a capped
    re-verify RE-VERIFIES previously-verified pairs instead of silently
    pruning them from the rewritten palette (the cross-model No-ship catch —
    a routine re-verify must never strand a fleet whose pair is still valid).
    The cap bounds only the discovery flood; a pair leaves the palette solely
    by failing verification or by leaving the candidates file — both honest.

    Args:
        candidates: (provider, model) pairs, in file order.
        per_provider: Max candidates to keep per provider.
        always_keep: Pairs kept even beyond the cap (not counted toward it).

    Returns:
        The capped list, preserving the input order.
    """
    seen: dict[str, int] = {}
    capped: list[tuple[str, str]] = []
    for pair in candidates:
        if pair in always_keep:
            capped.append(pair)
            continue
        provider = pair[0]
        count = seen.get(provider, 0)
        if count < per_provider:
            capped.append(pair)
            seen[provider] = count + 1
    return capped


def _verifying_banner(to_verify: list[tuple[str, str]], total: int) -> str:
    """Build the pre-spend disclosure banner printed before the first paid call.

    States the X-of-Y split honestly (KTD4): when nothing was trimmed
    (``len(to_verify) == total`` — either ``--all`` was passed, or every
    provider was already at or under the cap), it says "all N" and never
    mentions the cap or ``--all`` — implying a trim happened when it didn't
    would be misleading. When capped, it also names exactly which pairs will
    be verified, so the operator sees the spend commitment up front rather
    than discovering it call-by-call.

    Discovered candidate strings are untrusted display input (KTD9) — each
    provider/model piece is routed through the sanitize chokepoint before
    joining, the same per-field pattern ``cli.py``'s ``validate_command`` uses
    (sanitize each piece, not the assembled line — a hostile value can't then
    forge the ``, `` separator into a fake extra pair).
    """
    footer = (
        "Unsupported or unauthenticated ones are skipped (a skip is normal, not\n"
        "an error). Provider output is hidden; set CADRE_VERIFY_VERBOSE=1 to show it."
    )
    if len(to_verify) == total:
        return f"Verifying all {total} discovered candidate(s) against this host —\n{footer}\n"

    shown = ", ".join(f"{_sanitize(p)} / {_sanitize(m)}" for p, m in to_verify)
    return (
        f"Verifying {len(to_verify)} of {total} discovered candidate(s) against this host\n"
        f"({_DEFAULT_PER_PROVIDER_CAP} per provider by default; pass --all to verify all "
        f"{total}):\n"
        f"  {shown}\n\n"
        f"{footer}\n"
    )


def _existing_palette_pairs(palette_path: Path) -> set[tuple[str, str]]:
    """The (provider, model) pairs on the EXISTING palette, or empty.

    ``write_palette`` rewrites ``palette.yaml`` from a pass's records only —
    it never merges the prior palette (verified-truth-per-cycle). ``main``
    therefore feeds these pairs back in two ways: as ``_cap_candidates``'s
    ``always_keep`` set (a capped re-verify RE-VERIFIES them rather than
    silently pruning them — the cross-model No-ship catch), and to warn about
    the remainder (pairs no longer in the candidates file at all, which WILL
    drop). Tolerant read — an absent/unreadable/malformed existing palette
    returns empty (the malformed case is preflight's business, not this
    disclosure's).
    """
    try:
        data = yaml.safe_load(palette_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, yaml.YAMLError):
        return set()
    if not isinstance(data, dict) or not isinstance(data.get("models"), list):
        return set()
    existing: set[tuple[str, str]] = set()
    for entry in data["models"]:
        if isinstance(entry, dict):
            provider, model = entry.get("provider"), entry.get("model")
            if isinstance(provider, str) and isinstance(model, str):
                existing.add((provider, model))
    return existing


def _entry_policy_banned(entry: object, policy: Policy) -> bool:
    """True iff a palette ``models`` entry is a well-formed pair the policy bans.

    Checks the entry against ``policy.check`` — the SAME authoritative,
    case-insensitive gate preflight enforces — rather than a candidate-derived
    pair set, so the prune catches a policy-banned palette entry whatever its
    casing and even if it is no longer in the candidates file. A non-dict or
    non-string-pair entry is never "banned" (it is preserved verbatim; it was
    never a runnable pair to begin with).
    """
    if not isinstance(entry, dict):
        return False
    provider, model = entry.get("provider"), entry.get("model")
    if not isinstance(provider, str) or not isinstance(model, str):
        return False
    return policy.check(provider, model) is not None


def _prune_banned_from_palette(palette_path: Path, policy: Policy) -> None:
    """Rewrite an existing palette.yaml with its policy-banned entries removed.

    Called only from ``main``'s all-excluded branch (#85): every candidate is
    policy-banned, so nothing is re-verified this cycle. Without this, a TOTAL
    ban would leave an existing palette — and its generated fleet — still
    advertising a now-banned pair, breaking the prune promise exactly when the
    ban is total. (The partial-ban path already prunes, because ``write_palette``
    rewrites from the surviving verified records; only the total-ban path,
    which returns before ``write_palette``, missed it.)

    Reads the existing palette and drops every entry the POLICY bans — checked
    directly against ``policy.check`` (``_entry_policy_banned``), the same
    case-insensitive gate preflight uses, NOT a candidate-derived pair set — so
    a banned palette entry is pruned regardless of its casing and even if it is
    no longer among the candidates. Rewrites via the canonical owner-only atomic
    writer (``approval._write_owner_only`` — temp + ``os.replace``, no
    truncation on a mid-write failure). The SURVIVING entries and the file's own
    ``toolsets`` are preserved VERBATIM — no re-verification, no invented
    verification claims — and ``generated_at`` is carried over unchanged when
    present. A fully-pruned palette is written with an empty ``models`` list
    (preflight then refuses every fleet as off-palette, the correct posture when
    every pair is banned), since ``write_palette`` cannot express a zero-pair
    palette.

    Then applies the SAME palette-fleet rule the verify path uses, to the
    pruned set: ``write_palette_fleet`` on records reconstructed from the
    survivors. 2+ surviving providers regenerates the smoke-test fleet without
    the banned pair; fewer leaves any prior fleet in place with a loud stderr
    notice (a run against it is correctly refused at preflight) — mirroring the
    verify path exactly rather than inventing a removal rule.

    No-op (leaves the file byte-untouched) when there is no readable existing
    palette, or when NONE of its entries is banned — a total ban that does not
    actually touch the palette must not perturb it. Never raises: a write
    failure warns to stderr, matching the already-exit-1 all-banned posture.
    """
    try:
        data = yaml.safe_load(palette_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, yaml.YAMLError):
        return
    if not isinstance(data, dict) or not isinstance(data.get("models"), list):
        return

    models = data["models"]
    survivors = [entry for entry in models if not _entry_policy_banned(entry, policy)]
    if len(survivors) == len(models):
        return  # no in-palette pair is banned — nothing to prune, leave as-is

    toolsets = data.get("toolsets")
    if not isinstance(toolsets, list):
        toolsets = []
    generated_at = data.get("generated_at")
    if not isinstance(generated_at, str) or not generated_at:
        generated_at = datetime.now().isoformat()
    palette = {"generated_at": generated_at, "models": survivors, "toolsets": toolsets}
    content = _PALETTE_HEADER + yaml.safe_dump(palette, sort_keys=False, allow_unicode=True)
    try:
        _write_owner_only(palette_path, content)
    except OSError as exc:
        # A write failure (symlinked target, unsafe parent) must not crash the
        # already-failing (exit 1) all-banned path — warn and move on, the same
        # never-crash posture the verify path's write_palette_fleet hook holds.
        print(
            f"[cadre] warning: could not prune banned pair(s) from {palette_path}: {exc}",
            file=sys.stderr,
        )
        return

    # Mirror the verify path's fleet hook on the pruned set: the survivors were
    # verified in a prior cycle and remain on the palette, so reconstruct ok
    # records and re-run the same generator (in the palette's own order).
    survivor_records = [
        VerifyRecord(provider=entry["provider"], model=entry["model"], ok=True)
        for entry in survivors
        if isinstance(entry, dict) and entry.get("provider") and entry.get("model")
    ]
    fleet_path = palette_path.parent / "fleets" / "palette-fleet.yaml"
    write_palette_fleet(survivor_records, path=fleet_path)


def main(all_candidates: bool = False) -> int:
    """Verify candidates against this host and write the palette (R5, R6).

    By default, verifies a capped subset (``_DEFAULT_PER_PROVIDER_CAP`` per
    provider, in file order — ``_cap_candidates``) rather than every
    discovered candidate: zero-touch discovery (#61) can surface ~70 pairs
    across a handful of providers, and paying for 70 calls before the palette
    is even usable is needless spend. Pass ``all_candidates=True`` (the CLI's
    ``--all`` flag) to verify every discovered candidate instead. Either way,
    the X-of-Y split (``_verifying_banner``) prints BEFORE the first paid call
    (``verify_candidates``, below) — the spend commitment is disclosed up
    front, never discovered call-by-call or after the fact.

    The #78 policy gate runs before any of that: a malformed policy file
    refuses outright (fail closed, no candidates even loaded for display —
    KTD2), and every policy-banned candidate is filtered out of the working
    candidate list BEFORE the cap/always-keep logic ever sees it — so a
    banned pair is refused admission before any (paid) call AND, if it was
    already on the existing palette, PRUNED from the rewritten one: it can
    never land in ``always_keep`` (that set only matters for pairs that
    remain in the candidate list) and so cannot survive the cap it would
    otherwise be exempt from. This deliberately overrides the always-keep /
    cap-exempt invariant for exactly this case (KTD4) — a tightened policy
    must be able to evict a pair the operator previously trusted.

    Args:
        all_candidates: Verify every discovered candidate, bypassing the
            per-provider cap. Defaults to False (the capped subset).

    Returns:
        0 on a successful write (at least one candidate verified ok); 1 if
        the policy file is malformed, there are no candidates to verify (or
        none survive policy filtering), or the palette write itself failed
        (a clean message is printed either way — never a raw traceback).
    """
    candidates_path = _DEFAULT_CANDIDATES_PATH.expanduser()
    palette_path = _DEFAULT_PALETTE_PATH.expanduser()

    try:
        policy_path = resolve_policy_path()
        # Pass no path so load_policy derives the override source from the env
        # (CADRE_POLICY vs the default) — an absent DEFAULT stays permissive,
        # while an absent CADRE_POLICY-named file fails closed (#85).
        policy = load_policy()
    except PolicyError as exc:
        print(_sanitize(str(exc)))
        return 1

    candidates, declared_toolsets = _load_candidates(candidates_path)

    if not candidates:
        print(
            "No candidates found. Either:\n"
            f"  • Populate {candidates_path} with a 'candidates' list — run "
            "`cadre setup` to seed it from the installed package, or\n"
            "  • Edit PROVIDERS in this file (a dev/source-checkout shortcut; "
            "not durable across a package reinstall/upgrade)"
        )
        return 1

    # Read once, early: both the policy-exclusion disclosure right below (to
    # tell an EVICTION of a previously-trusted pair apart from skipping a new
    # candidate) and the cap/always-keep logic further down need the existing
    # palette's pairs.
    existing = _existing_palette_pairs(palette_path)

    # #78: banned candidates are refused BEFORE any paid call — filtered out
    # of the working list here, before the cap/always-keep logic below ever
    # runs, so verify_candidates() is never even invoked for them.
    candidates, policy_violations = filter_pairs(candidates, policy)
    for v in policy_violations:
        # A violating pair already on the existing palette is being EVICTED —
        # that must read differently from merely skipping a new candidate
        # that was never admitted in the first place.
        eviction = " — pruned from your palette" if (v.provider, v.model) in existing else ""
        print(
            f"[cadre] policy: excluded {_sanitize(v.provider)}/{_sanitize(v.model)} "
            f"({_sanitize(v.rule)}) — not sent for verification{eviction}",
            file=sys.stderr,
        )

    if not candidates:
        # FOLD 3 (#85): every candidate is policy-banned, so nothing is
        # re-verified this cycle — but an existing palette (and its generated
        # fleet) may still advertise a now-banned pair. Prune those in-palette
        # violations before returning, so the TOTAL-ban case honors the same
        # prune promise the partial-ban path already keeps. The per-pair
        # "pruned from your palette" disclosure already fired in the loop above.
        # The prune re-checks each existing entry against the policy directly
        # (authoritative, case-insensitive) rather than the candidate-derived
        # violation set, so it also evicts a banned palette entry no longer in
        # the candidates file.
        _prune_banned_from_palette(palette_path, policy)
        print(
            f"All {len(policy_violations)} candidate(s) are excluded by policy "
            f"({_sanitize(str(policy_path))}) — nothing to verify."
        )
        return 1

    total = len(candidates)
    # Cross-model No-ship catch: a re-verify must never silently prune a
    # previously-verified pair. Existing-palette pairs still in the candidates
    # file are ALWAYS re-verified (exempt from the cap); the cap bounds only
    # the discovery flood.
    to_verify = (
        candidates
        if all_candidates
        else _cap_candidates(candidates, always_keep=frozenset(existing))
    )

    # Pre-spend disclosure #2: pairs on the existing palette that are no
    # longer in the candidates file at all cannot be re-verified and WILL
    # drop when the palette is rewritten. Warn loudly BEFORE the first paid
    # call so the operator can abort and re-add them. Policy-banned pairs are
    # excluded from this set — they already got their own, correctly-attributed
    # disclosure above; without this exclusion a pruned pair would ALSO trigger
    # this generic "no longer in the candidates file" warning, which is both
    # factually wrong (it IS still in the file — policy excluded it) and a
    # confusing double warning for the same pair.
    policy_banned_pairs = {(v.provider, v.model) for v in policy_violations}
    dropping = sorted(existing - set(to_verify) - policy_banned_pairs)
    if dropping:
        shown = ", ".join(f"{_sanitize(p)}/{_sanitize(m)}" for p, m in dropping)
        print(
            f"[cadre] warning: {len(dropping)} previously-verified pair(s) are no "
            f"longer in the candidates file and will DROP from the palette: {shown}\n"
            "  The palette is rewritten from this pass only. To keep them, add "
            "them back to ~/.cadre/palette-candidates.yaml first (re-running "
            "`cadre discover` regenerates that file from the current inventory). "
            "Fleets composed from dropped pairs will be refused at preflight.",
            file=sys.stderr,
        )

    print(_verifying_banner(to_verify, total))
    records = verify_candidates(to_verify)

    n_ok = sum(1 for r in records if r.ok)
    try:
        write_palette(records, declared_toolsets, palette_path)
    except (ValueError, OSError) as exc:
        # ValueError: zero verified providers (nothing to write). OSError: a
        # write failure — including O_NOFOLLOW's ELOOP when ~/.cadre/palette.yaml
        # is a planted symlink (the correct fail-closed behavior). Degrade to a
        # clean message + nonzero exit, never a raw traceback.
        print(f"\n✗ {exc}")
        return 1

    print(f"\n✓ {n_ok} of {len(records)} verified → {palette_path}")
    # Same KTD9 rule as verify_candidates' per-candidate lines: discovered
    # strings render sanitized, per field.
    skipped = [f"{_sanitize(r.provider)}/{_sanitize(r.model)}" for r in records if not r.ok]
    if skipped:
        print(f"  skipped {len(skipped)}: {', '.join(skipped)}")

    # Bonus artifact (U5, #61): a runnable smoke-test fleet from the just-verified
    # pairs, written as a sibling "fleets/" dir of wherever palette.yaml just
    # landed — deliberately derived from palette_path rather than a second
    # independent ~/.cadre-rooted default: every existing test above reaches
    # this point only after patching _DEFAULT_PALETTE_PATH to a tmp path, and
    # deriving from it (instead of a standalone constant no test knows to
    # patch) keeps those tests hermetic for free, with no changes to them.
    # write_palette_fleet NEVER raises — a fleet-write failure (or too few
    # verified providers) warns to stderr but must not flip this successful
    # verify to a nonzero exit; palette.yaml above is the primary deliverable.
    fleet_path = palette_path.parent / "fleets" / "palette-fleet.yaml"
    write_palette_fleet(records, path=fleet_path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
